### ISSUE TITLE
Stream support for uploading images

### ISSUE THREAD

**Issue by adamburgess** [DamienDennehy/Imgur.API#1]
It would be lovely if you could add this. I only have VS2013 installed, so I can't create a PR myself...

If possible, supporting PushStreamContent would be even better, which would allow me to do things like:

``` C#
using (var bmp = new Bitmap(256, 256))
using (var gfx = Graphics.FromImage(bmp))
{
    gfx.DrawString("nice library btw", SystemFonts.DefaultFont, SystemBrushes.InfoText, 0, 0);

    var imgur = new ImageEndpoint(new ImgurClient(ImgurClientId, ImgurClientSecret));
    imgur.UploadImagePushStreamAsync(new PushStreamContent((stream, _, __) =>
    {
        bmp.Save(stream, ImageFormat.Png);
    }));
}
```

as it stands, the library uses double the memory as I need to write the bmp to a MemoryStream, which is copied to another byte array, which is then wrapped by your library in another MemoryStream (ByteArrayContent also exists, so wrapping it in a stream isn't necessary either)

**Comment by DamienDennehy** [comment]
I have a large release in the works with AccountEndpoint functionality in the next week or so, but I'll take a look at this after before I work on any new features.

**Comment by adamburgess** [comment]
thanks!

**Comment by DamienDennehy** [comment]
I added Stream support to 3.1.0-alpha1. There's a noticeable difference in memory usage.

**Uploading Bytes - 3.2MB image**
![3mb_img_withbytes](https://cloud.githubusercontent.com/assets/3924814/11023805/983567ec-867a-11e5-8cb7-048b58969e7d.png)

**Uploading Stream - 3.2MB image**
![3mb_img_withstream](https://cloud.githubusercontent.com/assets/3924814/11023806/9838ab1e-867a-11e5-9727-f009a8698231.png)

I decided not to use PushStreamContent for the time being as it requires System.Net.Http to be added to the project, and I'm trying for now to keep the size of the package as small as possible.

**Comment by adamburgess** [comment]
ah, ok.
Those memory decreases are great. Thanks for this!
