### ISSUE TITLE
Image upload timeout

### ISSUE THREAD

**Issue by mrousavy** [DamienDennehy/Imgur.API#11]
On uploading larger Images to Imgur, the upload will be cancelled and an error occurs.

**Comment by DamienDennehy** [comment]
The default timeout is 100 seconds....are you seeing uploads taking longer than that?

**Comment by mrousavy** [comment]
Sometimes it fails after 60 secs (exactly), with images even smaller than 1KB (i tested by limiting bandwidth), can you make the timeout a parameter or is it set on Imgur's servers?

**Comment by DamienDennehy** [comment]
I can make the timeout configurable, but if Imgur's servers cut it off after 60 seconds I can't do much about that.

**Comment by mrousavy** [comment]
I just looked up the Image Endpoint in the documentation, would've been faster than posting a ticket.

So the timeout is apparently not a [parameter](https://api.imgur.com/endpoints/image)
