### ISSUE TITLE
Upload GIFvs and Images larger than 10MB

### ISSUE THREAD

**Issue by mrousavy** [DamienDennehy/Imgur.API#15]
The official Imgur JSON API only supports binary images up to **10MB**, but by using *custom Web Requests* that can be bypassed (See [ShareX's Imgur Uploader](https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/ImageUploaders/Imgur.cs))

ShareX's uploader lib can upload GIFvs and Images over 10 MB in file size.

**Comment by DamienDennehy** [comment]
I can look into this later on in June but I'm tied up until then on another project.

Happy to accept a PR on this however if you want to work on it yourself.

**Comment by DamienDennehy** [comment]
Very late to the party here, but resolved in v5.0.0.
