### ISSUE TITLE
Feature request: Swagger

### ISSUE THREAD

**Issue by phl3x0r** [DamienDennehy/Imgur.API#19]
Would it be possible to make a swagger document of the API available?
This would really help in creating API libs for different languages/frameworks.

Thanks. :-)

**Comment by DamienDennehy** [comment]
Swagger is designed for REST APIs. Imgur themselves would have to add this to their APIs as this project is just a wrapper around that. From researching it I don't think Swagger can be generated from a NuGet package (needs ASP.NET Core etc), but if I'm wrong and there is a method please let me know.
