### ISSUE TITLE
Uploading file with clientId and clientSecret does the upload anonymously 

### ISSUE THREAD

**Issue by stefanMinch3v** [DamienDennehy/Imgur.API#21]
When i try to upload image with my clientId and clientSecrets, the image doesn't appear in my imgur profile but at some random place on website.
Code example: https://pastebin.com/PxRX4krQ

**Comment by asiryan** [comment]
@stefanMinch3v , @DamienDennehy hello! How can I upload images to my account? NOT anonymosly. I use client Id and client secret, bu my images stored in random place on imgur. What I should do?
