### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ntanfat** [DamienDennehy/Imgur.API#3]

**Comment by DamienDennehy** [comment]
It's an Async method. You're missing the await.

image = **await** endpoint.UploadImageStreamAsync(fs);

**Comment by kidbandes** [comment]
Sorry, i forgot that await :), i tried again, but i got another issue

CS4033: The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.

At the line: image = await endpoint.UploadImageStreamAsync(fs);

Am i missing some reference? Here are my using

using Imgur.API;
using Imgur.API.Authentication.Impl;
using Imgur.API.Endpoints.Impl;
using Imgur.API.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

And these in Web.config

<assemblies>
        <add assembly="System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
        <add assembly="System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
        <add assembly="System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
      </assemblies>

**Comment by DamienDennehy** [comment]
The error is correct. Your method definition should be an async one.

```
    public async Task UploadImage()
    {
        //Upload code here
    }
```

If you haven't used Async programming before you might want to do some reading first.
