### ISSUE TITLE
Anonymous usage, Should have override without secret

### ISSUE THREAD

**Issue by ghost** [DamienDennehy/Imgur.API#4]
Anonymous usage can be done without providing a secret and only a client ID. Would appreciate support for that.

**Comment by DamienDennehy** [comment]
Yeah I can see a use for that. I took a look at the use of the client secret and it's only used for OAuth authentication so should be a minor addition. I'm doing a beta2 release of v3.7.0 in a few days so I'll try and fit that in.

**Comment by DamienDennehy** [comment]
Resolved in v3.7.0-beta2.
