### ISSUE TITLE
Unable to Open Project File in VS2015

### ISSUE THREAD

**Issue by SkyEngine-OSP** [DamienDennehy/Imgur.API#6]
the title says it all. i am not able to open the project in Visual Studio 2015, can you please upgrade it so that users like me that runs VS2015 can open the API ? thank you

**Comment by DamienDennehy** [comment]
Install Visual Studio 2015 Update 3 and .NET Core 1.0.0 - VS 2015 Tooling Preview 2 and try again.

https://go.microsoft.com/fwlink/?LinkId=691129
https://go.microsoft.com/fwlink/?LinkID=824849
