### ISSUE TITLE
Including url in description has randomly added spaces between periods.

### ISSUE THREAD

**Issue by Bitz** [DamienDennehy/Imgur.API#8]
Consuming model via

> IImage image = await endpoint.UploadImageUrlAsync(model.Url, null, model.Title, model.Description);

Where model.Description is a string of value "http://google.com"

When posted, the url shows up as "http://google . com"

**Comment by DamienDennehy** [comment]
I'm not seeing this behavior I'm afraid, I created a test console for it...

```
        static void Main(string[] args)
        {
           SpaceTestAsync().GetAwaiter().GetResult();
        }

        static async Task SpaceTestAsync()
        {
            var client = new ImgurClient("YOUR_ID");
            var endpoint = new ImageEndpoint(client);

            var uploadedImage = await endpoint.UploadImageUrlAsync(
                "http://i.imgur.com/Eg71tvs.gif",
                null, "http://google.com", "http://google.com");

            var image = await endpoint.GetImageAsync(uploadedImage.Id);

            Console.Write(image.Description);
        }
```

I've tried 3 or 4 times and I'm getting "http://google.com" consistently.

**Comment by Bitz** [comment]
My bad, it seems like the bug won't happen with non-sub domain links. Try making the description something along the lines of

> http://bitzleon.tumblr.com/post/107075026520/owlturdcomix-and-then-you-respawn-image

to replicate the issue.

**Comment by DamienDennehy** [comment]
The good news is I can replicate it, the bad news I can't fix it. 
It looks like something Imgur is doing itself in their API.

I used Fiddler to submit 2 raw requests to Imgur...

This request puts spaces in the URL:
`type=URL&image=http%3A%2F%2Fi.imgur.com%2FEg71tvs.gif&description=http%3A%2F%2Fbitzleon.tumblr.com%2Fpost%2F107075026520%2Fowlturdcomix-and-then-you-respawn-image `

This request does not:
`type=URL&image=http%3A%2F%2Fi.imgur.com%2FEg71tvs.gif&description=http%3A%2F%2Fbitzleonx.tumblrx.com%2Fpost%2F107075026520%2Fowlturdcomix-and-then-you-respawn-image`

It's something to do with the tumblr URL maybe? Very strange.

**Comment by briancrink** [comment]
I too have encountered this bug. Added a github url to the description of a photo in a gallery album on Imgur. Imgur places spaces between periods in urls. I don't know the cause but it's certainly not resolved.

**Comment by davidagross** [comment]
So I just posted a workaround here

[How to add a hyperlink / anchor to an image description?](https://community.imgur.com/t/how-to-add-a-hyperlink-anchor-to-an-image-description/18820/20?u=dgroseph)

that involves replacing all problematic periods with their HTML code [\&#46;](https://www.toptal.com/designers/htmlarrows/punctuation/period/).  Very silly that this works and that this hasn't been shared as a solution, to my knowledge, for all these years.

**Comment by 6MB11** [comment]
I’ve submitted this to Imgur via their feature suggestion feature to avoid the use of `&#46;`

**Comment by 6MB11** [comment]
Imgur gave me a response that basically says that accounts with lower than 50 reputation can’t post links to combat past issues with spammer abuse.

![C26C3C7D-B438-452B-994D-3445E4944A8B](https://user-images.githubusercontent.com/45149917/85494993-b3448700-b5a7-11ea-99a0-47845f1b7e1c.jpeg)

Also & coincidentally, the newest beta may have broken the `&#46;` workaround
